# Configuration of python script for data generation
output: "output.txt"
grid_size: [1024, 2048, 4096]
calculate_BW: true
voxelization_tech: 1
thresh_raycasting: 0.000001
png: true
ply: false
csv: false
hec: false
