# Configuration of python script for data generation
output: "output.txt"
grid_size: [1024]
calculate_BW: true
voxelization_tech: 1
thresh_raycasting: 0.000001
png: false
ply: false
csv: false
hec: true
